var MSG = {
	blocks: "Blocs",
	trashTooltip: "Supprimer tous les blocs.",
	catLogic: "Logique",
	catLoops: "Boucles",
	catMath: "Math",
	catText: "Texte",
	catLists: "Listes",
	catColour: "Couleurs",
	catVariables: "Variables",
	catFunctions: "Fonctions",
	listVariable: "liste",
	textVariable: "texte",
	xmlError: "Impossible de charger le fichier de sauvegarde.  Peut être a t-il été créé avec une autre version de Blockly ?",
	badXml: "Erreur d’analyse du fichier :\n%1\n\nSélectionner 'OK' pour abandonner vos modifications ou 'Annuler' pour continuer à modifier le fichier.",
	languageSpan: "choix de la langue",
	themeSpan: "choix du thème",
	uploadButton_span: "Téléverser",
	resetButton_span: "Réinitialiser",
	trashButton_span: "Supprimer tous les blocs",
	saveCodeButton_span: "Exporte le code Arduino",
	saveXMLButton_span: "Enregistrer le fichier Blockly",
	loadXMLfakeButton_span: "Ouvrir un fichier Blockly"
};
