//Classic Theme
Blockly.Themes.Classic.setCategoryStyle('arduino_category',{
    "colour":"#007481"
});
Blockly.Themes.Classic.setCategoryStyle('seeed_category',{
    "colour":"#91C11E"
});
Blockly.Themes.Classic.setCategoryStyle('grove_category',{
    "colour":"#018770"
});
Blockly.Themes.Classic.setCategoryStyle('servo_category',{
    "colour":"#343434"
});
//Dark Theme
Blockly.Themes.Dark.setCategoryStyle('arduino_category',{
    "colour":"#007481"
});
Blockly.Themes.Dark.setCategoryStyle('seeed_category',{
    "colour":"#91C11E"
});
Blockly.Themes.Dark.setCategoryStyle('grove_category',{
    "colour":"#018770"
});
Blockly.Themes.Dark.setCategoryStyle('servo_category',{
    "colour":"#343434"
});
//High Contrast theme
Blockly.Themes.HighContrast.setCategoryStyle('arduino_category',{
    "colour":"#007481"
});
Blockly.Themes.HighContrast.setCategoryStyle('seeed_category',{
    "colour":"#91C11E"
});
Blockly.Themes.HighContrast.setCategoryStyle('grove_category',{
    "colour":"#018770"
});
Blockly.Themes.HighContrast.setCategoryStyle('servo_category',{
    "colour":"#343434"
});
//Modern theme
Blockly.Themes.Modern.setCategoryStyle('arduino_category',{
    "colour":"#007481"
});
Blockly.Themes.Modern.setCategoryStyle('seeed_category',{
    "colour":"#91C11E"
});
Blockly.Themes.Modern.setCategoryStyle('grove_category',{
    "colour":"#018770"
});
Blockly.Themes.Modern.setCategoryStyle('servo_category',{
    "colour":"#343434"
});