var MSG = {
	blocks: "Blocks",
	trashTooltip: "Discard all blocks.",
	catLogic: "Logic",
	catLoops: "Loops",
	catMath: "Math",
	catText: "Text",
	catLists: "Lists",
	catColour: "Colour",
	catVariables: "Variables",
	catFunctions: "Functions",
	listVariable: "list",
	textVariable: "text",
	xmlError: "Could not load your saved file. Perhaps it was created with a different version of S4E?",
	badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the file.",
	languageSpan: "choose language",
	themeSpan: "choose  theme",
	uploadButton_span: "Upload",
	resetButton_span: "Reset",
	trashButton_span: "Delete all blocks",
	saveCodeButton_span: "Export Arduino Code",
	saveXMLButton_span: "Save to file",
	loadXMLfakeButton_span: "Load file"
};
