var MSG = {
    blocks: "ブロック",
    trashTooltip: "すべてのブロックを消します。",
    catLogic: "論理",
    catLoops: "繰り返し",
    catMath: "数学",
    catText: "テキスト",
    catLists: "リスト",
    catColour: "色",
    catVariables: "変数",
    catFunctions: "関数",
    listVariable: "リスト",
    textVariable: "テキスト",
    xmlError: "保存されたファイルを読み込めませんでした。別のバージョンのブロックリーで作成された可能性があります。",
    badXml: "XML のエラーです:\n%1\n\nXML の変更をやめるには「OK」、編集を続けるには「キャンセル」を選んでください。",
    languageSpan: "choose language",
    themeSpan: "choose  theme",
    boardSpan: "choose board",
    uploadButton_span: "Upload",
    resetButton_span: "Reset",
    trashButton_span: "Delete",
    saveCodeButton_span: "Save Arduino Code",
    saveXMLButton_span: "Save XML",
    loadXMLfakeButton_span: "Load XML",
    accessibilitySpan: "Enable Accessibility Mode:",
    defaultCursorSpan: "Default Cursor",
    basicCursorSpan: "Basic Cursor",
    keyMappingSpan: "Open Key Mappings",
    themeClassicSpan: "Classic",
    themeModernSpan: "Modern",
    themeHighContrastSpan: "High Contrast",
    themeDarkSpan: "Dark",
    themeBwSpan: "Black & White",
    keyMappingSetSpan: "Set key mappings below",
    accessibilityExplanationSpan: "You can enter accessibility mode by <b>shift clicking anywhere on the workspace or on a block</b>. <br /><br /><b>Workspace Navigation</b><br />W: Previous block/field/input at the same level<br />A: Up one level (Field (or input) -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Stack -&gt; Workspace)<br />S: Next block/field/input at the same level<br />D: Down one level (Workspace -&gt; Stack -&gt; Block -&gt; Input (or field) -&gt; Block -&gt; Field (or input))<br />T: Will open the toolbox. Once in there you can moving around using the WASD keys. And insert a block by hitting Enter<br />X: While on a connection hit X to disconnect the block after the cursor<br /><br /><b>Cursor</b><br /><b>Default Cursor:</b> Allow the user to go to the previous, next, in or out location.<br /><b>Basic Cursor:</b> Using the pre order traversal allows the user to go to the next and previous location.</td>"
};
